---
title: "Security Phishing Project"
author: "Emily Port"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(reshape2)
```


```{r outlook-plots}

outlook_data <- data.frame(
  Pi_inbox = 3,
  Pi_spam = 115,
  Llama_inbox = 4,
  Llama_spam = 122,
  ChatGPT_inbox = 2,
  ChatGPT_spam = 70,
  Enron_Inbox = 59,
  Enron_spam = 37
)

outlook_data <- melt(outlook_data, variable.name = "Category", value.name = "Count")

print(outlook_data)

distribution_plot <- outlook_data %>%
  ggplot(aes(x = Category, y = Count, fill = Category)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  ylim(0, 125)+
  scale_fill_brewer(palette = "Paired") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Outlook Inbox and Spam Counts by LLM", x = "LLM and Class", y = "Count")

distribution_plot

```


```{r yahoo-plots}

yahoo_data <- data.frame(
  Pi_inbox = 35,
  Pi_spam = 80,
  Llama_inbox = 35,
  Llama_spam = 92,
  ChatGPT_inbox = 30,
  ChatGPT_spam = 36,
  Enron_Inbox = 48,
  Enron_spam = 45
)

yahoo_data <- melt(yahoo_data, variable.name = "Category", value.name = "Count")

print(yahoo_data)

distribution_plot_yahoo <- yahoo_data %>%
  ggplot(aes(x = Category, y = Count, fill = Category)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  ylim(0, 125)+
  scale_fill_brewer(palette = "Paired") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Yahoo Inbox and Spam Counts by LLM", x = "LLM and Class", y = "Count")

distribution_plot_yahoo

```

```{r}

yahoo_data <- data.frame(
  Pi_inbox = 35,
  Pi_spam = 80,
  Llama_inbox = 35,
  Llama_spam = 92,
  ChatGPT_inbox = 30,
  ChatGPT_spam = 36,
  Enron_inbox = 48,
  Enron_spam = 45
)

outlook_data <- data.frame(
  Pi_inbox = 3,
  Pi_spam = 115,
  Llama_inbox = 4,
  Llama_spam = 122,
  ChatGPT_inbox = 2,
  ChatGPT_spam = 70,
  Enron_inbox = 59,
  Enron_spam = 37
)

combined_df <- full_join(outlook_data, yahoo_data, by = intersect(names(outlook_data), names(yahoo_data))) %>%
  summarise(across(everything(), sum, na.rm = TRUE))

print(combined_df)

data_with_percentage <- combined_df %>%
  mutate(
    Pi_spam_percentage = Pi_spam / (Pi_spam + Pi_inbox) * 100,
    Llama_spam_percentage = Llama_spam / (Llama_spam + Llama_inbox) * 100,
    ChatGPT_spam_percentage = ChatGPT_spam / (ChatGPT_spam + ChatGPT_inbox) * 100,
    Enron_spam_percentage = Enron_spam / (Enron_spam + Enron_inbox) * 100
  )

print(data_with_percentage)
```

